---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  rename(latitude = lat, longitude = long) %>%
  select(
    boro = neighbourhood_group, neighbourhood, rating, price, room_type,
    latitude, longitude) %>%
  filter(!is.na(rating))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boros = nyc_airbnb %>% distinct(boro) %>% pull()

# selectInput widget
selectInput(
  "boro_choice", 
  label = h3("Select boro"),
  choices = boros, selected = "Manhattan")


max_price = 1000
min_price = nyc_airbnb %>% distinct(price) %>% min()
  
# sliderInput widget
sliderInput(
  "price_range", 
  label = h3("Choose price range"), 
  min = min_price, max = max_price, value = c(100, 400))

room_choice = nyc_airbnb %>% distinct(room_type) %>% pull()

# radioButtons widget
radioButtons(
  "room_choice", 
  label = h3("Choose room type"),
  choices = room_choice, selected = "Entire home/apt")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlot({
  nyc_airbnb %>%
  filter(
    boro == input$boro_choice, 
    price %in% input$price_range[1]:input$price_range[2],
    room_type == input$room_choice) %>%
  ggplot(aes(x = latitude, y = longitude, color = price)) + 
  geom_point(alpha = .5)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlot({
  nyc_airbnb %>% 
    filter(
      boro == input$boro_choice, 
      price %in% input$price_range[1]:input$price_range[2],
      room_type == input$room_choice) %>%
    count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  ggplot(aes(x = neighbourhood, y = n)) + 
  geom_bar(stat = "identity")
})
```

### Chart C

```{r}
renderPlot({ 
  common_neighborhoods =
    nyc_airbnb %>% 
    filter(
      boro == input$boro_choice,
      price %in% input$price_range[1]:input$price_range[2],
      room_type == input$room_choice) %>%
    count(neighbourhood, sort = TRUE) %>% 
    top_n(8) %>% 
    select(neighbourhood)

  nyc_airbnb %>%
    filter(
      boro == input$boro_choice,
      price %in% input$price_range[1]:input$price_range[2],
      room_type == input$room_choice) %>%
    inner_join(., common_neighborhoods, by = "neighbourhood") %>% 
    ggplot(aes(x = neighbourhood, y = price)) + 
    geom_boxplot()
})
```

